### ISSUE TITLE
Create a script for KB statistics

### ISSUE THREAD

**Issue by TramsWang** [TramsWang/KBRedundancies#9]
- Language: Python > 3.7
- Input: Numerated KB format
- Output: An **Excel** spreadsheet file that contains the following sheets:
  1. Overview
     -  1st row, the title row:
        - `KB`: the name of the KB
        - `#relations`: the number of different relations
        - `#entities`: the number of different entities
        - `#classes`: the number of classes in the KB
        - `avg. degr.`: the average degree of entities in the KB
     -  2nd row is for the corresponding values
  2. Relations
     - 1st row, the title row: 
        - `relation`: the relation name
        - `id`: mapped numerical id of the relation
        - `#instances`: the number of records/triples in this relation
        - `prop. (%)`: the proportion of the relation in the entire KB, round to 2 decimal places
        - `property`: whether the relation is a property
        - `reified`: whether the relation is based on reified records/triples
        - `#entities`: the number of different entities involved in the relation
        - `#subjects`: the number of different subjects involved in the relation
        - `#objects`: the number of different objects involved in the relation
        - `functionality`: the functionality value of the relation, round to 2 decimal places
        - `symmetricity`: the proportion of symmetric pairs in the relation, round to 2 decimal places
     - other rows are the statistics of each relation

**Comment by sjtu-ren** [comment]
<img width="617" alt="WechatIMG128" src="https://user-images.githubusercontent.com/87291924/170459779-aa67f971-7155-4eb1-a038-2f678dfed640.png">
学长，关于截图的这几点有几个疑问：
 1. 对于property、reified：因为现在KB的格式中，relation相当于是只存了他有哪些tuples，然而这个relation的语义是没有存储的，因此直接从现有的relation数据结构提取这两个性质，可能会比较困难。我想到的两个解决方案是：1. 在生成excel的脚本中增加与用户的交互，由于relation的name是含有语义的，人就可以通过自己的判断，提取出其中的语义；2. 或者去找一些自动化的判断工具。（reified这个概念也不是很明白）
 2. functionality：和1一样，也是现有的relation数据结构不满足需求的问题。我看了下yago的relation中是包含该数据的，所以，我想到的解决方案是对每个relation加一些需要的属性，然后用json格式存下来，每次load/dump的时候，加载或修改该文件。
 3. subjects和objects：这两个概念不是很明白，希望学长可以解释一下。

**Comment by TramsWang** [comment]
1. 是否是`property`的判别办法是看这个关系的宾语是否是一些原始类型（primitive type）的数据，比如`int`,`string`之类。`reified`的含义是一个triple的主语或宾语不是实体，而是其他的triple。这个字段在Yago里可能可以做到，其他的数据库目前还不清楚。我记得Yago里给每个triple都加了一个ID，当这个ID作为一个triple的主语或者宾语出现的时候，那么这个triple就是一个reified triple。在当前信息里不好做出判断的时候可以先空着。
2. functionality的定义可以参见AMIE的文章，它通过一个主语对应的宾语数量定义。这个可以算出来。
3. `#subjects`指一个relation中，所有triple的主语的值的集合的大小。`#objects`则是对于宾语而言。例如，一个relation中包含这三个triples：`(s1, r, o1)`, `(s1, r, o2)`, `(s3, r, o3)`，则`#subjects=|{s1, s3}|=2`, `#objects=|{o1, o2, o3}|=3`

**Comment by sjtu-ren** [comment]
学长，关于`property`的判断有个问题：我看了yago1论文的`data model`的部分，yago对`string`都是当作`entity`来处理的，那原始类型的`string`和不是原始类型的`string`就不太好区分。比如：Alice is a Person和Alice wins NobelPrice，person是原始类型而NobelPrice则不是，但在当前的模型下，没有足够的信息可以直接区分。我目前只统计了日期、type的宾语这些可以确定的，但对于那些可能是原始类型，但又难以区分的`string`就不知道怎么处理，想问下学长这部分有没有什么好的办法。

**Comment by sjtu-ren** [comment]
学长，关于`numerateKB`有个问题，就是根据数据集路径去初始化得到一个`numerateKB`的时候，`yago1`提取出来就会把服务器30GB的内存都吃满，这样进行后续的分析提取时，可用内存就非常少，提取两个relation的信息就会跑不下去。想问下我们服务器的物理内存大概多少，是不是可以给sinc分的多一点或者有没有其他的解决方案？

**Comment by TramsWang** [comment]
1. 从Yago的Data Model部分来看，它并不区分relation和property，所有的三元组都是`<entity, relation, entity>`的简单模型。咱们现在先把Yago中的所有关系都当做非property看待吧。我的印象里有的KG是区分普通relation和实体的property的，我当时还困惑了很久（现在还是有点困惑）。咱们再多观察一些KG后再回来思考一下这个问题。我觉得对于当前主流KG来说，可能的一个方案是这样：**只作为宾语出现的entity是表示属性的特殊实体，而以这些特殊实体为宾语的关系是表示属性的关系，即property**。

2. 有几个思路可以尝试解决一下：
   1. 直觉来说系统的内存不应该被消耗这么多，用资源管理器（可以用`htop`命令查看）查看一下在加载KB之前是不是内存就已经被占用很多了，因为这台机器还有另一个学生在使用；
   2. 在分析完一个relation之后直接释放内存资源；
   3. 我在[SInC](https://github.com/TramsWang/SInC)中添加了一个新branch：`v2`，里面包含了Java版本的NumeratedKB的实现，尝试一下Java版本的会不会好一些；
   3. 手动Load单独的KBRelation实例，不通过NumeratedKB类型加载，使用完之后释放内存。
